name: Test And Coverage Report

on:
  push:
    branches: ["feature/**", "master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        xcode: ["14.2"]
        macos: ["macos-latest"]
        scheme: ["workflows"]
        command: ["test"]
        platform: ["iOS"]
        workspace: ["workflows/workflows.xcodeproj"]
        exclude:
          - macos: "macos-11"
            xcode: "12.0.1"
          - macos: "macos-10.15"
            xcode: "13.0"
          - macos: "macos-10.15"
            xcode: "12.5.1"
          - platform: "watchOS"
            xcode: "12.0.1"
    steps:
      - name: Switch xcode to ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Double-check macOS version (${{ matrix.macos }})
        run: sw_vers
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: list files
        run: ls
      - name: Check xcodebuild version
        run: xcodebuild -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -showsdks
      - name: Show buildable schemes
        run: xcodebuild -list
      - name: Show eligible build destinations for ${{ matrix.scheme }}
        run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
      - uses: mxcl/xcodebuild@v2.0.0
        with:
          xcode: ${{ matrix.xcode }}
          workspace: ${{ matrix.workspace }} 
          platform: ${{ matrix.platform }}
          scheme: ${{ matrix.scheme }}
          action: ${{ matrix.command }}
          code-coverage: true
          verbosity: xcpretty
          upload-logs: always

      - name: Test coverage
        uses: maxep/spm-lcov-action@0.3.1
        with:
          output-file: ./coverage/lcov.info
